apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: python-ado-agent
spec:
  template:
    metadata:
      labels:
        name: python-ado-agent
    spec:
      serviceAccountName: azure-devops
      containers:
      - name: python-ado-agent
        image: ado-agent/python-ado-agent
        env:
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: python-ado-agent-access-token
        - name: AGENT_POOL
          value: default
        - name: AGENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SERVER_URL
          value: https://dev.azure.com/ChadHamilton
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/sh
                - -c
                - ./config.sh remove --unattended --token $ACCESS_TOKEN
  replicas: 5
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - python-ado-agent
      from:
        kind: ImageStreamTag
        name: python-ado-agent:latest
